### ISSUE TITLE
ERROR found line with forbidden symbols HADEG_protein_database_231119.faa that is '{' (/^[^a-z#>]/i)

### ISSUE THREAD

**Issue by YouCook21** [jarojasva/HADEG#1]
Hi,

I think there is bug in the program. Following the instruction,

- I created a new folder where to store the *.faa file coming from a previous annotation

`mkdir annot_files`
`cp ~/path/to/annotation/*faa annote_files`

- Then I downloaded the HADEG_protein_database_231119.faa file placing it in the same folder
`cd annot_files`
`wget https:/path/to/github/link/of/HADEG_protein_database_231119.faa`

- After that I launched the script as reported in the README
`cd ..`
`proteinortho annot_files/*.faa -identity=50 -conn=0.3 -project=Results_HADEG_Sind`

However, I got this error, and as far as I can understand it's related to the HADEG_protein_database_231119.faa file:

[Error]  
ERROR found line with forbidden symbols in 'annot_files/HADEG_protein_database_231119.faa' that is '{' (/^[^a-z#>]/i)
full line:
**lot of output lines**

Any ideas?

**Comment by jarojasva** [comment]
Hello. It seems that the character '{' is in the file HADEG_protein_database_231119.faa. Is it possible that you opened it and placed that character by accident? I downloaded the file from GitHub, and it doesn't contain that character. I look forward to your response. Regards, Jorge

**Comment by YouCook21** [comment]
Hi Jorge,
I re-downloaded the HADEG fasta file without `wget` and re-launched the program. Now it's working.
Really dunno what happened the first time!

Thank you very much and sorry for the inconvenience :)

All the bests,

Claudio
